### PR TITLE
Update to reflect new release and website.

### PR DESCRIPTION
**Pull request by andDevW**
I have an update of getChromium that I haven't been able to merge on GitLab due to some issues with GitLab.

### CODE REVIEW

**Comment by Bubu** [comment]
github is not the right place for this, as none of the fdroiddata contributors even has merge access to this mirror.

Has the gitlab issue been resolved?

**Comment by andDevW** [comment]
No. No idea what's wrong with it. If somebody wants to update it I'll put the F-droid link back up on my app page.

**Comment by Bubu** [comment]
Addedn v4.1 in https://gitlab.com/fdroid/fdroiddata/commit/a319af194d6aeabe20422589a79db8cda5a4cfdb and also enabled auto-updates.

Please use gitlab for this in the future, we have CI configured there, etc. and nobody checks here...

**Comment by andDevW** [comment]
Thanks, will do.

**Pull request closed without merging**
